import type { PizzaOrder } from "./types"

export const pizzaOrders: PizzaOrder[] = [
  {
    orderId: "PZA001",
    customerName: "John Doe",
    pizzaType: "Margherita",
    quantity: 2,
    orderDate: "2023-05-15T14:30:00",
    status: "delivered",
  },
  {
    orderId: "PZA002",
    customerName: "Jane Smith",
    pizzaType: "Pepperoni",
    quantity: 1,
    orderDate: "2023-05-15T15:45:00",
    status: "preparing",
  },
  {
    orderId: "PZA003",
    customerName: "Robert Johnson",
    pizzaType: "Veggie Supreme",
    quantity: 3,
    orderDate: "2023-05-15T16:20:00",
    status: "pending",
  },
  {
    orderId: "PZA004",
    customerName: "Emily Davis",
    pizzaType: "Hawaiian",
    quantity: 2,
    orderDate: "2023-05-15T17:10:00",
    status: "out-for-delivery",
  },
  {
    orderId: "PZA005",
    customerName: "Michael Brown",
    pizzaType: "BBQ Chicken",
    quantity: 1,
    orderDate: "2023-05-15T18:05:00",
    status: "cancelled",
  },
  {
    orderId: "PZA006",
    customerName: "Sarah Wilson",
    pizzaType: "Meat Lovers",
    quantity: 2,
    orderDate: "2023-05-16T12:15:00",
    status: "delivered",
  },
  {
    orderId: "PZA007",
    customerName: "David Taylor",
    pizzaType: "Buffalo Chicken",
    quantity: 1,
    orderDate: "2023-05-16T13:30:00",
    status: "preparing",
  },
  {
    orderId: "PZA008",
    customerName: "Jennifer Martinez",
    pizzaType: "Cheese",
    quantity: 4,
    orderDate: "2023-05-16T14:45:00",
    status: "pending",
  },
  {
    orderId: "PZA009",
    customerName: "Thomas Anderson",
    pizzaType: "Supreme",
    quantity: 2,
    orderDate: "2023-05-16T15:20:00",
    status: "out-for-delivery",
  },
  {
    orderId: "PZA010",
    customerName: "Lisa Garcia",
    pizzaType: "Mushroom",
    quantity: 1,
    orderDate: "2023-05-16T16:10:00",
    status: "delivered",
  },
  {
    orderId: "PZA011",
    customerName: "Daniel Rodriguez",
    pizzaType: "Spinach & Feta",
    quantity: 2,
    orderDate: "2023-05-17T11:30:00",
    status: "pending",
  },
  {
    orderId: "PZA012",
    customerName: "Amanda Lee",
    pizzaType: "Veggie",
    quantity: 1,
    orderDate: "2023-05-17T12:45:00",
    status: "preparing",
  },
  {
    orderId: "PZA013",
    customerName: "Kevin White",
    pizzaType: "Pepperoni & Mushroom",
    quantity: 3,
    orderDate: "2023-05-17T13:15:00",
    status: "delivered",
  },
  {
    orderId: "PZA014",
    customerName: "Melissa Clark",
    pizzaType: "Sausage",
    quantity: 2,
    orderDate: "2023-05-17T14:30:00",
    status: "out-for-delivery",
  },
  {
    orderId: "PZA015",
    customerName: "Christopher Lewis",
    pizzaType: "Bacon",
    quantity: 1,
    orderDate: "2023-05-17T15:20:00",
    status: "cancelled",
  },
]
